[package]
name = "doculock"
version = "1.0.0"
edition = "2024.beta"

[addresses]
doculock = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
